config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
#  match 'work/index', to: 'work#index', via: 'get'
#  match 'work', to: 'work#index', via: 'get'

  match 'work/choose_theme', to: 'work#choose_theme', via: :get, :as=>'choose_theme'

  match 'work/display_theme', to: 'work#display_theme', via: :post

  resources :themes
  resources :values
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  # root 'main#index'
  # get 'main/index'

  match 'main/help', to: 'main#help', via: 'get'

  get 'main/contacts'

  get 'main/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do

    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get

  end
  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  match 'help',     to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'

  match 'work',             to: 'work#index',             via: 'get'
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'

  match 'save_value',       to: 'api/api#save_value',   via: :get
end

app/views/shared/_footer.html.haml
%div.clearblock
%footer
  %div.footer-block
    %div.socials
      = link_to image_tag("vkontakte.png", alt: "vk",  style: "width: 45%")
      = link_to image_tag("facebook.png", alt: "vk",  style: "width: 45%")
      = link_to image_tag("google.png", alt: "vk",  style: "width: 45%")
    .copy
      %i.fa.fa-copyright.iconsMain
        2016 Experteese


app/views/shared/_header.html.haml
%header
  %div.header-block
    %ul.nav.navbar-nav.pull-left
      %p.locale

      -#.ru_link
      = link_to image_tag("ru_flag.jpg", alt: "",  style: "width: 5%; height: 5%", title: "Русский" ), locale: :ru
      = link_to image_tag("en_flag.jpg", alt: "",  style: "width: 4.5%; height: 4.5%", title: "English"), locale: :en
      %b
        = I18n.locale
      -#= link_to image_tag("logo.jpg", alt: "",  style: "width: 20%; height: 20%")

    %nav
      %ul.nav.navbar-nav.pull-right

        -#%li= link_to t('.help'), help_path
        - if signed_in?
          -#%li= link_to "Users", '#'

          %ul.nav.navbar-nav.pull-right
            %li= link_to t('.work'), work_path
            %li= link_to t('.profile'), current_user
            -#%li= link_to t('.settings'), '#'
            %li.divider
            %li
              = link_to t('.sign_out'), signout_path, method: "delete"

            %li.logged
              #{current_user.name}
            -#= gravatar_for current_user

        - else
          %li= link_to t('.sign_in'), signin_path
%div.empty